"""add health report tables

Revision ID: 75dfc3797480
Revises: d15bd00e7eac
Create Date: 2026-02-02 01:01:18.697963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75dfc3797480'
down_revision: Union[str, Sequence[str], None] = 'd15bd00e7eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_gender', sa.String(), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_reports_user_id'), 'health_reports', ['user_id'], unique=False)
    op.create_table('health_report_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['health_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_report_messages_report_id'), 'health_report_messages', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_report_messages_report_id'), table_name='health_report_messages')
    op.drop_table('health_report_messages')
    op.drop_index(op.f('ix_health_reports_user_id'), table_name='health_reports')
    op.drop_table('health_reports')
    # ### end Alembic commands ###
