"""add_multiagent_fields_and_medical_reports

Revision ID: d15bd00e7eac
Revises: 127030e9f358
Create Date: 2026-01-28 15:52:53.776169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd15bd00e7eac'
down_revision: Union[str, Sequence[str], None] = '127030e9f358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('analysis_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_reports_session_id'), 'medical_reports', ['session_id'], unique=False)
    op.create_index(op.f('ix_medical_reports_user_id'), 'medical_reports', ['user_id'], unique=False)
    op.add_column('chat_messages', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chat_sessions', sa.Column('conversation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='voice_consultation'))
    op.add_column('chat_sessions', sa.Column('agent_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chat_sessions', sa.Column('session_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chat_sessions', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'summary')
    op.drop_column('chat_sessions', 'session_metadata')
    op.drop_column('chat_sessions', 'agent_used')
    op.drop_column('chat_sessions', 'conversation_type')
    op.drop_column('chat_messages', 'image_url')
    op.drop_index(op.f('ix_medical_reports_user_id'), table_name='medical_reports')
    op.drop_index(op.f('ix_medical_reports_session_id'), table_name='medical_reports')
    op.drop_table('medical_reports')
    # ### end Alembic commands ###
