"use client"
import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { useApiClient } from "@/lib/api"
import {
    ArrowLeft,
    Download,
    FileText,
    Calendar,
    Bot,
    User,
    Loader2,
    RefreshCw
} from 'lucide-react'
import { Button } from '@/components/ui/button'

type Message = {
    id: string
    role: string
    content: string
    created_at: string
}

type Summary = {
    session_id: string
    title: string
    conversation_type: string
    agent_used?: string
    summary: string
    generated_at: string
}

export default function SessionDetailPage() {
    const params = useParams()
    const sessionId = params.sessionId as string
    const apiClient = useApiClient()

    const [messages, setMessages] = useState<Message[]>([])
    const [summary, setSummary] = useState<Summary | null>(null)
    const [loading, setLoading] = useState(true)
    const [generatingSummary, setGeneratingSummary] = useState(false)

    useEffect(() => {
        loadSessionData()
    }, [sessionId])

    const loadSessionData = async () => {
        try {
            const response = await apiClient(`/history/sessions/${sessionId}`)
            setMessages(response.data)
        } catch (error) {
            console.error('Failed to load session:', error)
        } finally {
            setLoading(false)
        }
    }

    const generateSummary = async () => {
        setGeneratingSummary(true)
        try {
            const response = await apiClient(`/history/sessions/${sessionId}/summary`)
            setSummary(response.data)
        } catch (error) {
            console.error('Failed to generate summary:', error)
        } finally {
            setGeneratingSummary(false)
        }
    }

    const exportToPDF = () => {
        if (!summary) return

        // Create printable content
        const printContent = `
      <html>
        <head>
          <title>Medical Consultation Summary</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.6; }
            h1 { color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 10px; }
            h2 { color: #374151; margin-top: 20px; }
            .meta { color: #6b7280; font-size: 14px; margin-bottom: 20px; }
            .section { margin: 20px 0; }
            ul { margin: 10px 0; padding-left: 20px; }
            .footer { margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 20px; color: #9ca3af; font-size: 12px; }
          </style>
        </head>
        <body>
          <h1>Medical Consultation Summary</h1>
          <div class="meta">
            <p><strong>Session Title:</strong> ${summary.title}</p>
            <p><strong>Type:</strong> ${summary.conversation_type?.replace('_', ' ')}</p>
            ${summary.agent_used ? `<p><strong>Agent:</strong> ${summary.agent_used}</p>` : ''}
            <p><strong>Date:</strong> ${new Date(summary.generated_at).toLocaleDateString()}</p>
          </div>
          <div class="section">
            ${summary.summary.replace(/\*\*/g, '').replace(/##/g, '<h2>').replace(/\n/g, '<br>')}
          </div>
          <div class="footer">
            <p>Generated by AI Medical Assistant</p>
            <p>This summary is for informational purposes only and should not replace professional medical advice.</p>
          </div>
        </body>
      </html>
    `

        const printWindow = window.open('', '_blank')
        if (printWindow) {
            printWindow.document.write(printContent)
            printWindow.document.close()
            printWindow.print()
        }
    }

    const formatDate = (dateString: string) => {
        return new Date(dateString).toLocaleString()
    }

    return (
        <div className="p-6 max-w-4xl mx-auto">
            {/* Header */}
            <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-3">
                    <Link href="/dashboard/history">
                        <Button variant="ghost" size="icon">
                            <ArrowLeft className="w-5 h-5" />
                        </Button>
                    </Link>
                    <div>
                        <h1 className="text-xl font-bold text-gray-800">Session Details</h1>
                        <p className="text-sm text-gray-500">View conversation and generate report</p>
                    </div>
                </div>
                <div className="flex gap-2">
                    <Button
                        variant="outline"
                        onClick={generateSummary}
                        disabled={generatingSummary}
                    >
                        {generatingSummary ? (
                            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        ) : (
                            <RefreshCw className="w-4 h-4 mr-2" />
                        )}
                        Generate Summary
                    </Button>
                    {summary && (
                        <Button onClick={exportToPDF}>
                            <Download className="w-4 h-4 mr-2" />
                            Export PDF
                        </Button>
                    )}
                </div>
            </div>

            {/* Summary Card */}
            {summary && (
                <div className="bg-gradient-to-br from-blue-50 to-purple-50 rounded-2xl p-6 border mb-6">
                    <div className="flex items-center gap-2 mb-4">
                        <FileText className="w-5 h-5 text-blue-600" />
                        <h2 className="text-lg font-semibold text-gray-800">AI Summary Report</h2>
                    </div>
                    <div className="prose prose-sm max-w-none">
                        <div
                            dangerouslySetInnerHTML={{
                                __html: summary.summary
                                    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                                    .replace(/##\s?(.*?)\n/g, '<h3 class="text-base font-semibold mt-4 mb-2">$1</h3>')
                                    .replace(/\n/g, '<br>')
                            }}
                        />
                    </div>
                    <div className="mt-4 pt-4 border-t border-blue-200">
                        <p className="text-xs text-gray-500">
                            ⚠️ This summary is generated by AI for informational purposes only and should not replace professional medical advice.
                        </p>
                    </div>
                </div>
            )}

            {/* Conversation */}
            <div className="bg-white rounded-2xl border p-6">
                <h2 className="text-lg font-semibold text-gray-800 mb-4">Conversation History</h2>

                {loading ? (
                    <div className="text-center py-8 text-gray-400">
                        <Loader2 className="w-6 h-6 animate-spin mx-auto mb-2" />
                        Loading conversation...
                    </div>
                ) : messages.length === 0 ? (
                    <div className="text-center py-8 text-gray-400">
                        No messages found
                    </div>
                ) : (
                    <div className="space-y-4">
                        {messages.map((msg) => (
                            <div
                                key={msg.id}
                                className={`flex gap-3 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}
                            >
                                <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${msg.role === 'user' ? 'bg-blue-100' : 'bg-purple-100'
                                    }`}>
                                    {msg.role === 'user' ? (
                                        <User className="w-4 h-4 text-blue-600" />
                                    ) : (
                                        <Bot className="w-4 h-4 text-purple-600" />
                                    )}
                                </div>
                                <div className={`max-w-[80%] rounded-xl p-3 ${msg.role === 'user'
                                        ? 'bg-blue-50 text-gray-800'
                                        : 'bg-gray-50 text-gray-800'
                                    }`}>
                                    <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
                                    <p className="text-xs text-gray-400 mt-1">
                                        {formatDate(msg.created_at)}
                                    </p>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    )
}
