/**
 * ============================================================
 * MedSage Design Configuration
 * ============================================================
 * 
 * This is the single source of truth for ALL UI styling.
 * Change values here to update the entire app's look and feel.
 * 
 * HOW TO CUSTOMIZE:
 * 1. Colors     → Change `colors` object to update the app's palette
 * 2. Gradients  → Change `gradients` to update gradient combos
 * 3. Features   → Change `features` array to add/remove/reorder dashboard cards
 * 4. Sidebar    → Change `sidebar.navItems` to modify navigation
 * 5. Branding   → Change `branding` for app name, taglines, etc.
 * ============================================================
 */

// ─── BRANDING ──────────────────────────────────────────────
export const branding = {
    appName: "MedSage",
    tagline: "Your AI-powered medical assistant",
    welcomeMessage: "Your AI-powered medical assistant is ready to help. Start a consultation or explore our features below.",
    disclaimerText: "This report was generated by an AI Medical Assistant for informational purposes only. Always consult a qualified healthcare professional for medical advice.",
    badges: [
        { label: "HIPAA Compliant", icon: "shield" as const },
        { label: "AI Powered", icon: "zap" as const },
    ],
}

// ─── COLORS ────────────────────────────────────────────────
// Each feature has its own color scheme for easy customization
export const colors = {
    // Primary brand color (used for active states, CTAs)
    primary: {
        gradient: "from-blue-500 to-indigo-600",
        bg: "bg-blue-500",
        text: "text-blue-600",
        light: "bg-blue-50",
        shadow: "shadow-blue-500/20",
        ring: "ring-blue-500/30",
        border: "border-blue-200",
    },
    // Feature-specific colors
    voiceConsultation: {
        gradient: "from-blue-500 to-indigo-600",
        bg: "bg-blue-500/10",
        text: "text-blue-500",
        shadow: "shadow-blue-500/20",
    },
    medicalAssistant: {
        gradient: "from-purple-500 to-violet-600",
        bg: "bg-purple-500/10",
        text: "text-purple-500",
        shadow: "shadow-purple-500/20",
    },
    reportAnalysis: {
        gradient: "from-rose-500 to-pink-600",
        bg: "bg-rose-500/10",
        text: "text-rose-500",
        shadow: "shadow-rose-500/20",
    },
    xrayAnalysis: {
        gradient: "from-amber-500 to-orange-600",
        bg: "bg-amber-500/10",
        text: "text-amber-500",
        shadow: "shadow-amber-500/20",
    },
    bookDoctor: {
        gradient: "from-teal-500 to-emerald-600",
        bg: "bg-teal-500/10",
        text: "text-teal-500",
        shadow: "shadow-teal-500/20",
    },
    doctorPortal: {
        gradient: "from-indigo-500 to-purple-600",
        bg: "bg-indigo-500/10",
        text: "text-indigo-500",
        shadow: "shadow-indigo-500/20",
    },
    history: {
        gradient: "from-emerald-500 to-green-600",
        bg: "bg-emerald-500/10",
        text: "text-emerald-500",
        shadow: "shadow-emerald-500/20",
    },
    // Orb animation colors (voice consultation live session)
    orb: {
        speaking: {
            gradient: "from-teal-400 via-cyan-500 to-blue-500",
            glow: "from-teal-400/20 via-cyan-400/20 to-blue-400/20",
            shadow: "shadow-teal-500/40",
        },
        listening: {
            gradient: "from-blue-400 via-indigo-500 to-purple-500",
            glow: "from-blue-400/20 via-indigo-400/20 to-purple-400/20",
            shadow: "shadow-indigo-500/40",
        },
        idle: {
            gradient: "from-gray-400 to-gray-500",
            shadow: "shadow-gray-400/30",
        },
    },
    // Welcome banner gradient
    banner: {
        gradient: "from-blue-600 via-indigo-600 to-purple-700",
    },
}

// ─── GRADIENTS (Shortcuts) ─────────────────────────────────
export const gradients = {
    banner: `bg-gradient-to-r ${colors.banner.gradient}`,
    primary: `bg-gradient-to-br ${colors.primary.gradient}`,
    reportHeader: `bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600`,
    topAccent: `bg-gradient-to-r from-blue-500 via-indigo-500 to-purple-500`,
}

// ─── SIDEBAR NAVIGATION ───────────────────────────────────
export type NavItem = {
    label: string
    href: string
    icon: string // lucide-react icon name
    colorKey: keyof typeof colors
}

export const sidebarConfig = {
    navItems: [
        { label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard", colorKey: "primary" as const },
        { label: "Voice Consultation", href: "/dashboard/consultation", icon: "Mic", colorKey: "voiceConsultation" as const },
        { label: "Medical Assistant", href: "/dashboard/assistant", icon: "Bot", colorKey: "medicalAssistant" as const },
        { label: "Report Analysis", href: "/dashboard/report_analysis", icon: "FileText", colorKey: "reportAnalysis" as const },
        { label: "X-Ray Analysis", href: "/dashboard/xray_analysis", icon: "Activity", colorKey: "xrayAnalysis" as const },
        { label: "Book a Doctor", href: "/dashboard/consultation_booking", icon: "Calendar", colorKey: "bookDoctor" as const },
        { label: "History", href: "/dashboard/history", icon: "History", colorKey: "history" as const },
        { label: "Doctor Portal", href: "/dashboard/doctor-portal", icon: "Stethoscope", colorKey: "doctorPortal" as const },
    ],
    bottomItems: [
        { label: "Help & Support", href: "#", icon: "HelpCircle" },
        { label: "Settings", href: "#", icon: "Settings" },
    ],
}

// ─── DASHBOARD FEATURES ────────────────────────────────────
// Reorder, add, or remove items to change the dashboard cards
export const dashboardFeatures = [
    {
        title: "Voice Consultation",
        description: "Talk to specialized AI doctors for personalized medical advice",
        icon: "Mic",
        href: "/dashboard/consultation",
        colorKey: "voiceConsultation" as const,
    },
    {
        title: "Medical AI Assistant",
        description: "Chat, upload images, or record audio for AI-powered medical analysis",
        icon: "Bot",
        href: "/dashboard/assistant",
        colorKey: "medicalAssistant" as const,
    },
    {
        title: "Blood Report Analysis",
        description: "Upload blood test reports for AI interpretation and health insights",
        icon: "FileText",
        href: "/dashboard/report_analysis",
        colorKey: "reportAnalysis" as const,
    },
    {
        title: "Chest X-ray Analysis",
        description: "AI-powered pneumonia detection and chest X-ray interpretation",
        icon: "Activity",
        href: "/dashboard/xray_analysis",
        colorKey: "xrayAnalysis" as const,
    },
    {
        title: "Book a Doctor",
        description: "Schedule and join video consultations with healthcare specialists",
        icon: "Calendar",
        href: "/dashboard/consultation_booking",
        colorKey: "bookDoctor" as const,
    },
    {
        title: "History & Reports",
        description: "View past consultations and generate detailed summary reports",
        icon: "History",
        href: "/dashboard/history",
        colorKey: "history" as const,
    },
]

// ─── STATS (Dashboard banner) ──────────────────────────────
export const dashboardStats = [
    { label: "AI Agents", value: "6+", icon: "Bot" },
    { label: "Specialties", value: "10", icon: "Sparkles" },
    { label: "Reports", value: "0", icon: "FileText" }, // Updated dynamically
    { label: "Uptime", value: "99%", icon: "TrendingUp" },
]

// ─── LAYOUT ────────────────────────────────────────────────
export const layout = {
    sidebar: {
        expandedWidth: "260px",
        collapsedWidth: "72px",
    },
    content: {
        maxWidth: "max-w-6xl",
        padding: "p-6 lg:p-8",
    },
    borderRadius: {
        card: "rounded-2xl",
        button: "rounded-xl",
        badge: "rounded-full",
        input: "rounded-xl",
    },
}
