"""
AI Medical Report PDF Generator
Generates professional medical reports as downloadable PDFs.
Supports: Image analysis reports AND general conversation reports.
"""

import os
import io
import re
from datetime import datetime
from dataclasses import dataclass, field
from typing import Optional, List, Dict

from fpdf import FPDF


@dataclass
class DiagnosisReport:
    """Structured data for a medical AI diagnosis report."""
    # Patient info
    patient_name: str = "Patient"
    patient_gender: str = ""
    patient_dob: str = ""
    patient_blood_group: str = ""
    patient_bmi: str = ""
    patient_allergies: str = ""
    patient_conditions: str = ""
    patient_medications: str = ""
    
    # Analysis info
    agent_type: str = ""          # e.g. "BRAIN_TUMOR_AGENT"
    analysis_result: str = ""     # Full analysis text from the AI agent
    image_path: str = ""          # Path to the uploaded medical image
    heatmap_path: str = ""        # Path to Grad-CAM heatmap (if available)
    session_id: str = ""
    report_date: str = field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d %H:%M"))
    
    # Conversation messages (for general chat reports)
    # Each dict: {"role": "user"/"assistant", "content": str, "agent": str|None, "image_path": str|None}
    conversation_messages: List[Dict] = field(default_factory=list)


class MedicalReportPDF(FPDF):
    """Custom PDF layout for medical AI diagnosis reports."""
    
    HEADER_COLOR = (20, 90, 140)   # Dark medical blue
    ACCENT_COLOR = (45, 140, 190)  # Lighter blue for sections
    BG_LIGHT = (245, 248, 252)     # Subtle background tint
    TEXT_PRIMARY = (30, 30, 30)
    TEXT_SECONDARY = (100, 100, 100)
    USER_BG = (235, 242, 255)      # Light blue for user messages
    AI_BG = (240, 250, 240)        # Light green for AI messages
    
    def header(self):
        # Header bar
        self.set_fill_color(*self.HEADER_COLOR)
        self.rect(0, 0, 210, 22, "F")
        
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(255, 255, 255)
        self.set_y(5)
        self.cell(0, 12, "MedSage AI - Medical Report", align="C")
        self.ln(20)
    
    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*self.TEXT_SECONDARY)
        self.cell(0, 5, "DISCLAIMER: This report is generated by an AI system and is for informational purposes only.", align="C")
        self.ln(3)
        self.cell(0, 5, "It does NOT constitute a medical diagnosis. Always consult a qualified healthcare professional.", align="C")
        self.ln(4)
        self.set_font("Helvetica", "", 7)
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}  |  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C")
    
    def section_title(self, title: str):
        """Render a styled section heading."""
        self.ln(4)
        self.set_fill_color(*self.ACCENT_COLOR)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 11)
        safe_title = title.encode('latin-1', errors='replace').decode('latin-1')
        self.cell(0, 8, f"  {safe_title}", fill=True)
        self.ln(10)
        self.set_text_color(*self.TEXT_PRIMARY)
    
    def info_row(self, label: str, value: str):
        """Render a key-value information row."""
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*self.TEXT_SECONDARY)
        self.cell(50, 6, label)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*self.TEXT_PRIMARY)
        safe_value = (value if value else "N/A").encode('latin-1', errors='replace').decode('latin-1')
        self.cell(0, 6, safe_value)
        self.ln(6)


def _get_agent_display_name(agent_type: str) -> str:
    """Map agent type to a human-readable analysis title."""
    mapping = {
        "BRAIN_TUMOR_AGENT": "Brain Tumor Analysis (MRI)",
        "CHEST_XRAY_AGENT": "Chest X-ray COVID-19 Detection",
        "SKIN_LESION_AGENT": "Skin Lesion Segmentation Analysis",
        "CONVERSATION_AGENT": "General Medical Consultation",
        "RAG_AGENT": "Medical Knowledge Query",
        "SYMPTOM_AGENT": "Symptom Assessment",
        "TRIAGE_AGENT": "Medical Triage",
        "DIAGNOSTIC_AGENT": "Diagnostic Analysis",
        "SPECIALIST_AGENT": "Specialist Consultation",
        "META_AGENT": "Multi-Agent Consultation",
    }
    for key, val in mapping.items():
        if key in agent_type:
            return val
    return "Medical AI Consultation"


def _clean_markdown(text: str) -> str:
    """Strip markdown formatting and sanitize unicode for PDF text (latin-1 safe)."""
    # Remove bold/italic markers
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'\*(.+?)\*', r'\1', text)
    # Remove headers
    text = re.sub(r'^#{1,4}\s+', '', text, flags=re.MULTILINE)
    # Remove bullet markers (keep the text)
    text = re.sub(r'^[-•]\s+', '  - ', text, flags=re.MULTILINE)
    # Remove horizontal rules
    text = re.sub(r'^---+$', '', text, flags=re.MULTILINE)
    
    # Replace common unicode symbols with ASCII equivalents
    unicode_map = {
        '\u26a0': '[!]',    # ⚠ warning
        '\u26a0\ufe0f': '[!]',  # ⚠️ warning with variation selector
        '\u2705': '[OK]',   # ✅
        '\u274c': '[X]',    # ❌
        '\u2714': '[v]',    # ✔
        '\u2022': '-',      # •
        '\u2013': '-',      # –
        '\u2014': '--',     # —
        '\u2018': "'",      # '
        '\u2019': "'",      # '
        '\u201c': '"',      # "
        '\u201d': '"',      # "
        '\u2192': '->',     # →
        '\u2190': '<-',     # ←
        '\u2026': '...',    # …
        '\u00b7': '-',      # ·
        '\u25cf': '-',      # ●
        '\u25cb': 'o',      # ○
        '\u2502': '|',      # │
        '\u250c': '+',      # ┌
        '\u2510': '+',      # ┐
        '\u2514': '+',      # └
        '\u2518': '+',      # ┘
    }
    for char, replacement in unicode_map.items():
        text = text.replace(char, replacement)
    
    # Strip any remaining non-latin1 characters to prevent fpdf crash
    text = text.encode('latin-1', errors='replace').decode('latin-1')
    
    return text.strip()


def _get_agent_short_label(agent: str) -> str:
    """Short label for an agent in the conversation log."""
    labels = {
        "CONVERSATION_AGENT": "General AI",
        "RAG_AGENT": "Knowledge AI",
        "BRAIN_TUMOR_AGENT": "Brain Tumor AI",
        "CHEST_XRAY_AGENT": "X-Ray AI",
        "SKIN_LESION_AGENT": "Skin Lesion AI",
        "SYMPTOM_AGENT": "Symptom AI",
        "TRIAGE_AGENT": "Triage AI",
        "DIAGNOSTIC_AGENT": "Diagnostic AI",
        "SPECIALIST_AGENT": "Specialist AI",
        "META_AGENT": "Meta AI",
        "GUARDRAIL_AGENT": "Safety Check",
        "HUMAN_VALIDATED": "Validated",
    }
    for key, val in labels.items():
        if key in (agent or ""):
            return val
    return "AI Assistant"


def generate_diagnosis_pdf(report: DiagnosisReport) -> bytes:
    """
    Generate a professional PDF diagnosis report.
    
    Supports two modes:
    1. Image analysis reports (when image_path or analysis_result is set)
    2. Conversation reports (when conversation_messages is populated)
    
    Args:
        report: DiagnosisReport dataclass with all report data
        
    Returns:
        PDF file content as bytes
    """
    pdf = MedicalReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=25)
    
    # ── Report metadata ──
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*MedicalReportPDF.TEXT_SECONDARY)
    pdf.cell(0, 5, f"Report ID: {report.session_id[:8] if report.session_id else 'N/A'}   |   Date: {report.report_date}")
    pdf.ln(3)
    pdf.cell(0, 5, f"Analysis Type: {_get_agent_display_name(report.agent_type)}")
    pdf.ln(8)
    
    # ── Patient Information ──
    pdf.section_title("Patient Information")
    pdf.info_row("Name:", report.patient_name)
    if report.patient_gender:
        pdf.info_row("Gender:", report.patient_gender.capitalize())
    if report.patient_dob:
        pdf.info_row("Date of Birth:", report.patient_dob)
    if report.patient_blood_group:
        pdf.info_row("Blood Group:", report.patient_blood_group)
    if report.patient_bmi:
        pdf.info_row("BMI:", report.patient_bmi)
    if report.patient_allergies:
        pdf.info_row("Known Allergies:", report.patient_allergies)
    if report.patient_conditions:
        pdf.info_row("Chronic Conditions:", report.patient_conditions)
    if report.patient_medications:
        pdf.info_row("Current Medications:", report.patient_medications)
    
    # ── Medical Image (for image analysis reports) ──
    if report.image_path and os.path.exists(report.image_path):
        pdf.section_title("Uploaded Medical Image")
        try:
            img_x = (210 - 70) / 2  # center a 70mm wide image
            pdf.image(report.image_path, x=img_x, w=70)
            pdf.ln(5)
        except Exception:
            pdf.set_font("Helvetica", "I", 9)
            pdf.cell(0, 6, "[Image could not be loaded]")
            pdf.ln(5)
    
    # ── Grad-CAM Heatmap (for X-ray) ──
    if report.heatmap_path and os.path.exists(report.heatmap_path):
        pdf.section_title("Grad-CAM Visualization")
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(*MedicalReportPDF.TEXT_SECONDARY)
        pdf.cell(0, 5, "Highlighted regions indicate areas of interest detected by the AI model.")
        pdf.ln(6)
        try:
            img_x = (210 - 70) / 2
            pdf.image(report.heatmap_path, x=img_x, w=70)
            pdf.ln(5)
        except Exception:
            pass
    
    # ── Conversation Log (for all sessions with messages) ──
    if report.conversation_messages:
        pdf.section_title("Consultation Conversation")
        
        for msg in report.conversation_messages:
            role = msg.get("role", "")
            content = msg.get("content", "")
            agent = msg.get("agent", "")
            img_path = msg.get("image_path", "")
            
            if not content and not img_path:
                continue
            
            # Role label + background color
            if role == "user":
                pdf.set_fill_color(*MedicalReportPDF.USER_BG)
                label = "Patient"
                label_color = (30, 80, 160)
            else:
                pdf.set_fill_color(*MedicalReportPDF.AI_BG)
                label = _get_agent_short_label(agent) if agent else "AI Assistant"
                label_color = (30, 120, 60)
            
            # Message header with role label
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*label_color)
            pdf.cell(0, 5, label, fill=True)
            pdf.ln(5)
            
            # Message content
            if content:
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*MedicalReportPDF.TEXT_PRIMARY)
                clean = _clean_markdown(content)
                # Truncate extremely long messages to keep PDF reasonable
                if len(clean) > 2000:
                    clean = clean[:2000] + "\n... [truncated for report]"
                pdf.multi_cell(0, 4, clean)
            
            # Inline image (if user uploaded an image in this message)
            if img_path and os.path.exists(img_path):
                pdf.ln(2)
                try:
                    pdf.image(img_path, x=15, w=55)
                except Exception:
                    pdf.set_font("Helvetica", "I", 7)
                    pdf.cell(0, 4, "[Attached image could not be embedded]")
                pdf.ln(3)
            
            pdf.ln(3)
    
    # ── AI Analysis Summary (fallback for sessions without conversation_messages) ──
    elif report.analysis_result:
        pdf.section_title("AI Analysis Results")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*MedicalReportPDF.TEXT_PRIMARY)
        
        clean_text = _clean_markdown(report.analysis_result)
        pdf.multi_cell(0, 5, clean_text)
        pdf.ln(5)
    
    # ── Disclaimer Box ──
    pdf.ln(6)
    pdf.set_fill_color(255, 245, 230)  # Light warning yellow
    pdf.set_draw_color(220, 180, 80)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(140, 100, 20)
    pdf.cell(0, 7, "  Important Disclaimer", fill=True, border="LTR")
    pdf.ln(7)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_fill_color(255, 250, 240)
    disclaimer = (
        "This report has been generated by MedSage AI, an artificial intelligence-based medical "
        "analysis system. The results should NOT be considered as a definitive medical diagnosis. "
        "AI-generated analysis may contain inaccuracies. Always consult a qualified healthcare "
        "professional for proper diagnosis and treatment recommendations. Do not make medical "
        "decisions based solely on this report."
    )
    pdf.multi_cell(0, 4.5, disclaimer, fill=True, border="LBR")
    
    # Return as bytes
    return pdf.output()


def build_report_from_user_and_session(
    user, session, 
    analysis_result: str = "", 
    image_path: str = "", 
    heatmap_path: str = "",
    conversation_messages: list = None,
) -> DiagnosisReport:
    """
    Convenience factory to build a DiagnosisReport from a User ORM object and session data.
    
    Args:
        user: User SQLModel instance
        session: ChatSession SQLModel instance
        analysis_result: The AI agent's analysis text (for legacy image reports)
        image_path: Path to the uploaded medical image
        heatmap_path: Path to the Grad-CAM heatmap image (optional)
        conversation_messages: List of message dicts for conversation log
    """
    bmi_str = ""
    if user.height_cm and user.weight_kg:
        bmi = round(user.weight_kg / ((user.height_cm / 100) ** 2), 1)
        bmi_str = str(bmi)
    
    return DiagnosisReport(
        patient_name=user.name or "Patient",
        patient_gender=user.gender or "",
        patient_dob=user.date_of_birth or "",
        patient_blood_group=user.blood_group or "",
        patient_bmi=bmi_str,
        patient_allergies=user.allergies or "",
        patient_conditions=user.chronic_conditions or "",
        patient_medications=user.current_medications or "",
        agent_type=session.agent_used or "",
        analysis_result=analysis_result,
        image_path=image_path,
        heatmap_path=heatmap_path,
        session_id=str(session.id),
        conversation_messages=conversation_messages or [],
    )
